#!/bin/sh
# Echos "light" or "dark" to stdout
set -e

color_scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
if [ "$color_scheme" = "'prefer-dark'" ]; then # The single quotes are part of the string!
  echo dark
  exit 0;
fi

echo light
