#!/usr/bin/env bash

# Prevent pushing to protected branches directly
protected_pattern="master" # separate multiple patterns by | or leave empty.
if [ -n "$protected_pattern" ]
then
    protected_branches="^($protected_pattern)"
    current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

    if [[ "$current_branch" =~ $protected_branches ]]
    then
        read -p "You're about to push $current_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
        echo
        if echo $REPLY | grep -vE '^[Yy]$' > /dev/null
        then
            exit 1 # push will not execute
        fi
    fi
fi

# Git LFS, only runs when it's actually used in this repo
if git grep -q filter=lfs -- .gitattributes '**/.gitattributes' # https://stackoverflow.com/a/76197696
then
    command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path.\n"; exit 2; }
    git lfs pre-push "$@"
fi


